name: FloatingIslands
main: com.github.butterkeks_x86.floatingIslands.FloatingIslands
version: beta1.1
commands:
  floatingIslands:
    description: Join or leave the FloatingIslands realm
    usage: /floatingIslands join to enter the floating islands realm and /floatingIslands leave to leave it
    permissions: FloatingIslands.join
    permission-message: You don't have the permission to join the FloaringIslands realm
