name: FloatingIslands
main: com.github.butterkeks_x86.floatingIslands.FloatingIslands
version: 1.2beta
author: Butterkeks-x86 @Github
website: www.github.com/Butterkeks-x86/FloatingIslands
commands:
  floatingIslands:
    description: Join or leave the FloatingIslands realm.
    usage: "Usage: /<command> [help | join | leave]"
    aliases: [fi]
